

all: 01MPI_Intro 02MPI_pt2pt 03MPI_Coll 04MPI_Type 05MPI_Topo 06MPI_Miniapp 07MPI_Extra

01MPI_Intro:
	pdflatex 01.MPI_Intro.tex
	pdflatex 01.MPI_Intro.tex

02MPI_pt2pt:
	pdflatex 02.MPI_pt2pt.tex
	pdflatex 02.MPI_pt2pt.tex

03MPI_Coll:
	pdflatex 03.MPI_Coll.tex
	pdflatex 03.MPI_Coll.tex

04MPI_Type:
	pdflatex 04.MPI_Type.tex
	pdflatex 04.MPI_Type.tex

05MPI_Topo:
	pdflatex 05.MPI_Topo.tex
	pdflatex 05.MPI_Topo.tex

06MPI_Miniapp:
	pdflatex 06.MPI_Miniapp.tex
	pdflatex 06.MPI_Miniapp.tex

07MPI_Extra:
	pdflatex 07.MPI_Extra.tex
	pdflatex 07.MPI_Extra.tex

clean:
	rm -f 01.MPI_Intro.pdf 01.MPI_Intro.aux 01.MPI_Intro.dvi 01.MPI_Intro.log 01.MPI_Intro.nav 01.MPI_Intro.out 01.MPI_Intro.snm 01.MPI_Intro.toc 01.MPI_Intro.vrb 01.MPI_Intro.listing
	rm -f 02.MPI_pt2pt.pdf 02.MPI_pt2pt.aux 02.MPI_pt2pt.dvi 02.MPI_pt2pt.log 02.MPI_pt2pt.nav 02.MPI_pt2pt.out 02.MPI_pt2pt.snm 02.MPI_pt2pt.toc 02.MPI_pt2pt.vrb 02.MPI_pt2pt.listing
	rm -f 03.MPI_Coll.pdf 03.MPI_Coll.aux 03.MPI_Coll.dvi 03.MPI_Coll.log 03.MPI_Coll.nav 03.MPI_Coll.out 03.MPI_Coll.snm 03.MPI_Coll.toc 03.MPI_Coll.vrb 03.MPI_Coll.listing
	rm -f 04.MPI_Type.pdf 04.MPI_Type.aux 04.MPI_Type.dvi 04.MPI_Type.log 04.MPI_Type.nav 04.MPI_Type.out 04.MPI_Type.snm 04.MPI_Type.toc 04.MPI_Type.vrb 04.MPI_Type.listing
	rm -f 05.MPI_Topo.pdf 05.MPI_Topo.aux 05.MPI_Topo.dvi 05.MPI_Topo.log 05.MPI_Topo.nav 05.MPI_Topo.out 05.MPI_Topo.snm 05.MPI_Topo.toc 05.MPI_Topo.vrb 05.MPI_Topo.listing
	rm -f 06.MPI_Miniapp.pdf 06.MPI_Miniapp.aux 06.MPI_Miniapp.dvi 06.MPI_Miniapp.log 06.MPI_Miniapp.nav 06.MPI_Miniapp.out 06.MPI_Miniapp.snm 06.MPI_Miniapp.toc 06.MPI_Miniapp.vrb 06.MPI_Miniapp.listing
	rm -f 07.MPI_Extra.pdf 07.MPI_Extra.aux 07.MPI_Extra.dvi 07.MPI_Extra.log 07.MPI_Extra.nav 07.MPI_Extra.out 07.MPI_Extra.snm 07.MPI_Extra.toc 07.MPI_Extra.vrb 07.MPI_Extra.listing
	rm -f SummerSchool.conf.tex.aux SummerSchool.conf.aux
