

all: 01MPI_Intro 02MPI_pt2pt 03MPI_Coll 04MPI_Topo 05MPI_Type 06MPI_Miniapp

#all: 01MPI_Intro
#all: 02MPI_pt2pt
#all: 03MPI_Coll
#all: 04MPI_Topo
#all: 05MPI_Type
#all: 06MPI_Miniapp


01MPI_Intro:
	pdflatex 01.MPI_Intro.tex
	pdflatex 01.MPI_Intro.tex

02MPI_pt2pt:
	pdflatex 02.MPI_pt2pt.tex
	pdflatex 02.MPI_pt2pt.tex

03MPI_Coll:
	pdflatex 03.MPI_Coll.tex
	pdflatex 03.MPI_Coll.tex

04MPI_Topo:
	pdflatex 04.MPI_Topo.tex
	pdflatex 04.MPI_Topo.tex

05MPI_Type:
	pdflatex 05.MPI_Type.tex
	pdflatex 05.MPI_Type.tex

06MPI_Miniapp:
	pdflatex 06.MPI_Miniapp.tex
	pdflatex 06.MPI_Miniapp.tex

clean:
	rm -f 01.MPI_Intro.pdf 01.MPI_Intro.aux 01.MPI_Intro.dvi 01.MPI_Intro.log 01.MPI_Intro.nav 01.MPI_Intro.out 01.MPI_Intro.snm 01.MPI_Intro.toc 01.MPI_Intro.vrb
	rm -f 02.MPI_pt2pt.pdf 02.MPI_pt2pt.aux 02.MPI_pt2pt.dvi 02.MPI_pt2pt.log 02.MPI_pt2pt.nav 02.MPI_pt2pt.out 02.MPI_pt2pt.snm 02.MPI_pt2pt.toc 02.MPI_pt2pt.vrb
	rm -f 03.MPI_Coll.pdf 03.MPI_Coll.aux 03.MPI_Coll.dvi 03.MPI_Coll.log 03.MPI_Coll.nav 03.MPI_Coll.out 03.MPI_Coll.snm 03.MPI_Coll.toc 03.MPI_Coll.vrb
	rm -f 04.MPI_Topo.pdf 04.MPI_Topo.aux 04.MPI_Topo.dvi 04.MPI_Topo.log 04.MPI_Topo.nav 04.MPI_Topo.out 04.MPI_Topo.snm 04.MPI_Topo.toc 04.MPI_Topo.vrb
	rm -f 05.MPI_Type.pdf 05.MPI_Type.aux 05.MPI_Type.dvi 05.MPI_Type.log 05.MPI_Type.nav 05.MPI_Type.out 05.MPI_Type.snm 05.MPI_Type.toc 05.MPI_Type.vrb
	rm -f 06.MPI_Miniapp.pdf 06.MPI_Miniapp.aux 06.MPI_Miniapp.dvi 06.MPI_Miniapp.log 06.MPI_Miniapp.nav 06.MPI_Miniapp.out 06.MPI_Miniapp.snm 06.MPI_Miniapp.toc 06.MPI_Miniapp.vrb
